stages:
  - test
  - build
  - deploy
  - release

build-staging:
  stage: build
  image: registry.osrc.community/docker-images/dind:1.0
  only:
    - staging
  tags:
    - docker
  variables:
    IMAGE_TAG: staging
  before_script:
    - mkdir ~/".docker"
    - echo $DOCKER_AUTH_CONFIG > ~/".docker/config.json"
  script:
    - docker-compose -f docker-compose.build.yml build
    - docker-compose -f docker-compose.build.yml push

deploy-staging:
  stage: deploy
  image: registry.osrc.community/docker-images/dind:1.0
  only:
    - staging
  tags:
    - docker
  variables:
    IMAGE_TAG: staging
  before_script:
    - mkdir ~/".docker"
    - echo $DOCKER_AUTH_CONFIG > ~/".docker/config.json"
  script:
    - docker-compose -p "osrcc-tasknet" -f dcd.staging.yml up -d
