version: '3.7'

services:
  issue_board_frontend:
    image: registry.osrc.community/osrc-community/issue-board:frontend-staging
    container_name: staging_osrc-issue_board-frontend
    restart: unless-stopped
    networks:
      - web
      - osrc
  issue_board_backend:
    image: registry.osrc.community/osrc-community/issue-board:backend-staging
    container_name: staging_osrc-issue_board-frontend
    restart: unless-stopped
    networks:
      - web
      - osrc
networks:
  web:
    external: false
  osrc:
    external: true
