services:
  issue_board_frontend:
    image: registry.osrc.community/osrcc/tasknet:frontend-staging
    container_name: staging_osrc_tasknet-frontend
    restart: unless-stopped
    networks:
      - internal
      - cloudflare
  issue_board_backend:
    image: registry.osrc.community/osrcc/tasknet:backend-staging
    container_name: staging_osrc_tasknet-backend
    restart: unless-stopped
    networks:
      - internal
      - cloudflare

networks:
  internal:
    external: false
  cloudflare:
    external: true
